version: 0.0.{build}

platform: Any CPU
configuration: Release

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

before_build:
  nuget restore NLog.Targets.GraylogHttp.sln

build:
  parallel: true                
  project: NLog.Targets.GraylogHttp.sln
  verbosity: minimal
  publish_nuget: true